### ISSUE TITLE
Soft Delete interferes with PHPUnit Testing

### ISSUE THREAD

**Issue by NickBusey** [dereuromark/cakephp-tools#135] opened 2015-02-05 19:24 UTC
Running my tests, I get the following error:

```
Missing Database Table
Error: Table device for model Device was not found in datasource test.

Notice: If you want to customize this error message, create app/View/Errors/missing_table.ctp

Stack Trace
CORE/Cake/Model/Model.php line 3640 → Model->setSource(string)
CORE/Cake/Model/Model.php line 1387 → Model->getDataSource()
CORE/Cake/Model/Model.php line 1479 → Model->schema()
APP/Model/Behavior/SoftDeleteBehavior.php line 63 → Model->hasField(string)
CORE/Cake/Model/BehaviorCollection.php line 145 → SoftDeleteBehavior->setup(Device, array)
```

If I comment out the actsAs => SoftDelete line, it works fine.

Any ideas? Thanks much for all your work.

**Comment by dereuromark** [comment] 2015-02-05 20:14
Thats normal if u add the behavior
You didnt include the related fixtures then.

**Comment by NickBusey** [comment] 2015-02-05 20:38
Not sure what you mean? I do have fixtures included, and they work without the behavior.

**Comment by dereuromark** [comment] 2015-02-05 20:47
Did you also add the device table as the error warns about?

**Comment by NickBusey** [comment] 2015-02-06 02:53
Yes, as I said if I uncomment the SoftDelete behavior, it works as expected.

**Comment by dereuromark** [comment] 2015-02-06 08:23
I rather see a mistake in your model or fixture setup. Shoudnt device be plural devices?
Can you maybe bin your test code?

**Comment by NickBusey** [comment] 2015-02-07 21:31
Here's a simplified copy of the model and fixture code.

https://gist.github.com/NickBusey/4b309eb0c066fa8cd805

With actsAs SoftDelete it fails with a Missing Database Table error.

Comment out actsAs SoftDelete and it works.

**Comment by dereuromark** [comment] 2015-02-08 15:06
I still suspect the inflection to be the root cause of the issue here. Did you try using the conventions "devices" approach here for the table name?

**Comment by NickBusey** [comment] 2015-02-08 20:19
I changed 'device' to 'devices'. The web end works fine. Running the test, get the same error pointing now at 'devices'.

```
Missing Database Table
Error: Table devices for model Device was not found in datasource test.
```

**Comment by NickBusey** [comment] 2015-03-04 18:31
I'm going to assume this is an unknown issue with an unknown timeframe for a fix. I'm going to try and start debugging it.

**Comment by NickBusey** [comment] 2015-03-04 18:51
Commenting out Line 239 of SoftDeleteBehavior.php seems to fix the issue with the tests. The behavior functionality seems to work without this line.

**Comment by dereuromark** [comment] 2016-08-29 08:01
SoftDelete is deprecated and only 2.x needs fixing if someone is filling to provide a PR.

**Comment by dereuromark** [comment] 2016-09-20 08:52
Closing until PR is open.

**Closed by dereuromark** 2016-09-20 08:52 UTC
Labels: bug, hold
